### ISSUE TITLE
Minor ldyom bug report.

### ISSUE THREAD

**Issue by ghost** [MGeymer/LDYOM#15]
Ldyom can be toggled on/off with the "U" key on the pause menu, also the menu becomes un-clickable once toggled on.
Edit: If Ldyom is running in the background, it could be toggled on and off from the desktop itself!

**Comment by GeTechG** [comment]
Please specify the version of LDYOM, because the preview version has a different activation button and the code is completely rewritten, so you can't really tell if this bug still exists or not.

**Comment by Anime-Guy2000** [comment]
I am sorry I

**Comment by ghost** [comment]
Firstly, I am sorry. I didn't know about the other Beta 0.8.0 preview builds. This bug is from the stable release of Beta 0.7.2. But a _kinda_ similar bug exists on the latest preview build - When pausing the game and pressing 'I' a bunch of times and resuming, the menu flashes the exact number of times.

**Comment by GeTechG** [comment]
Okay, i try fix this.
