### ISSUE TITLE
Actors & Vehicles bug.

### ISSUE THREAD

**Issue by ghost** [MGeymer/LDYOM#17]
When you are in "edit manually" mode for a vehicle or actor and restart ldyom from the pause menu, the game crashes with the exception being that you won't be able to bring up the menu in case of actor.

**Comment by Anime-Guy2000** [comment]
Temporary fix for getting stuck: Open the mod menu > Tools > Antifreez (also an 'e' is missing in antifreeze).

**Comment by GeTechG** [comment]
Am I understanding you correctly that you started a new "new game" while editing?

**Comment by ghost** [comment]
> Am I understanding you correctly that you started a new "new game" while editing?

A new ldyom session from the pause menu, yes. Not the start of San Andreas storyline.
