### ISSUE TITLE
{Beta 0.8 preview 6 or older builds} Menu-camera shifting bug.

### ISSUE THREAD

**Issue by ghost** [MGeymer/LDYOM#27]
When u bring up the mod menu, move mouse around and close the menu the player's camera shifts to a different position in an instant.

**Comment by GeTechG** [comment]
Sorry but this is not a bug but normal, as the game sees that the mouse has moved and moves the camera.

**Comment by ghost** [comment]
No way to fix it?

**Comment by GeTechG** [comment]
I'll give it a try, but in general I'd focus primarily on problems that cause problems when creating (crashes, freezes, etc).

**Comment by GeTechG** [comment]
It seems to have been fixed, although the first time was still the same, the fact is that I took the code associated with the mouse and render from someone else, I don’t understand much about it.
