### ISSUE TITLE
Dragging objectives not implemented correctly.

### ISSUE THREAD

**Issue by ghost** [MGeymer/LDYOM#28]
Dragging objectives just moves them by 1 step at a time. For eg: If you want to drag the 1st obj to the last obj then its going to move 1 step down at a time until you reach the end & the obj number stays the same so you get situations like the last objective is #1.

**Comment by GeTechG** [comment]
1. Yes moving is not as convenient, but it works just 1 up and 1 down. Maybe later I will make it more convenient for now.
2. You may not know, but the RCM causes the target to change, and in all list boxes there is such a function. I will make a memo like everywhere else.

**Comment by ghost** [comment]
Thank You. I am actually waiting for the documentation to be completed (https://getechg.github.io/LDYOM_DOC/en/ ) but it still just has the standard "Hello World" text.

**Comment by GeTechG** [comment]
.
