### ISSUE TITLE
Actors and Vehicles "follow path" objective's route lines disappear near player.

### ISSUE THREAD

**Issue by ghost** [MGeymer/LDYOM#33]

**Comment by GeTechG** [comment]
This is normal because they are drawn on top of the game, in general I am not adding anything new to the game, this means that this will not be fixed simply because it needs to be rendered directly in the game itself.

**Comment by ghost** [comment]
After some testing, I think this has something to do with the player's camera, as from certain angles you can make the lines disappear.

> I am not adding anything new to the game.

I wanted to make some feature suggestions from the main game, DYOM and Mission Maker. It would be like a roadmap for the future. So should I or shouldn't?

**Comment by GeTechG** [comment]
> After some testing, I think this has something to do with the player's camera, as from certain angles you can make the lines disappear.

Yes, I hide the lines if one of the dots goes off the screen so they don't look distorted and bother my eyes.



> I wanted to make some feature suggestions from the main game, DYOM and Mission Maker. It would be like a roadmap for the future. So should I or shouldn't?

Yes you can, but it's better to do it in the LDYOM channel of discord. https://discord.gg/4KGf4Px
