### ISSUE TITLE
Checkpoints Problem.

### ISSUE THREAD

**Issue by ghost** [MGeymer/LDYOM#34]
In both cp types "Sphere" and "Race", 3 & 4 cps are the exact same. Also in case of Sphere cps, 3 & 4 don't display.

**Comment by GeTechG** [comment]
I added those that were in the game, perhaps they are really the same, I can only remove them.

**Comment by ghost** [comment]
If those are not bugs then I don't see the point in anyone using them. But from the "Race" type atleast 1 of those cps should remain.
