### ISSUE TITLE
Random Microsoft Visual C++ crash when restarting ldyom.

### ISSUE THREAD

**Issue by ghost** [MGeymer/LDYOM#36]
Loaded a scene from the 3 available selections and restarted ldyom.

**Microsoft Visual C++ Runtime Library error message:**

```
Debug Error!

Program: _path-to-game_\LDYOM_R.asi

abort() has been called

(Press Retry to debug the application)
```

**Comment by ghost** [comment]
Same error message when loading the only available mission in **production**.

**Comment by GeTechG** [comment]
Send it to me.

**Comment by ghost** [comment]
That's the only error message I got.
CrashInfo did'nt register the crash for some reason. You can try to recreate the same scenario from the instructions provided above.

**Comment by GeTechG** [comment]
Ah got it, it's ok because it's my missions that I forgot to delete, since they are preview versions there is no backwards compatibility in them.

**Comment by ghost** [comment]
Will backwards compatibility be implemented for the next preview?

**Comment by GeTechG** [comment]
No, it is in the release beta versions without the prefix preview, but this is not a guarantee, because something can change dramatically in the future, but in general I think it will no longer be in the next stable versions.
