### ISSUE TITLE
"Destroy Vehicle" objective markers.

### ISSUE THREAD

**Issue by ghost** [MGeymer/LDYOM#40]
Wrong marker color displayed for these colors - Light Blue, Purple, Cyan, Threat = Red (what's the difference?) & Destination = Yellow (what's the difference?).

**Comment by GeTechG** [comment]
I didn't find such a problem, I created the objective "Get in vehicle" and then on the checkpoint, and the label when you sit down is removed.

**Comment by ghost** [comment]
Only happens in "Destroy Vehicle" objective as mentioned above.

**Comment by GeTechG** [comment]
> During mission testing, the markers **don't** disappear after getting in the vehicle.

Then I don't understand why when you sit down he has to disappear?

**Comment by ghost** [comment]
It was actually just a feature request, much like "management issues" mission from the main storyline. Should have phrased the sentence better.

**Comment by GeTechG** [comment]
It is clear, then describe in more detail what exactly.

**Comment by ghost** [comment]
Its not a bug or any problem.
It was just a feature request and since you aren't focusing on implementing any new features, I will be adding that suggestion to the feature checklist. So if the marker colors are fixed you can close the issue.
