### ISSUE TITLE
Race-type checkpoint bugs.

### ISSUE THREAD

**Issue by ghost** [MGeymer/LDYOM#44]
Sphere-type 6 checkpoint is extremely glitchy and doesn't render/display during preview or in testing after its animation.

**Comment by GeTechG** [comment]
> Sphere-type 3 checkpoint doesn't render/display over radius value of 2.650.

This ring, it should be in the air. He just didn't have enough space, try to lift.

**Comment by ghost** [comment]
Bizarre, this issue isn't present in Sphere-type 4.
