### ISSUE TITLE
Getting "Wasted" or "Busted" during mission testing sends you to Hospital or Police Station, while also removes player's clothes.

### ISSUE THREAD

**Issue by ghost** [MGeymer/LDYOM#48]
Is this intentional behavior?

**Comment by GeTechG** [comment]
It's just an unhandled behavior, meaning the game itself does it by default. Again, not very much and want to do something about it as it does not affect it.

**Comment by ghost** [comment]
This wasn't the case with normal DYOM or MM, so decided to report it. You are right tho, it doesn't interfere with mission designing or gameplay. Still would be cool if it got fixed.
