### ISSUE TITLE
During object placement in "edit by camera"-mode you cannot set the camera's movement speed.

### ISSUE THREAD

**Issue by ghost** [MGeymer/LDYOM#53]

**Comment by GeTechG** [comment]
There are a lot of such places, I understand that you would like to restart LDYOM through the menu, but alas all places can not be fixed, you need to deal with each individual case. So my advice is to restart only with a complete reboot of the game.

**Comment by ghost** [comment]
> I understand that you would like to restart LDYOM through the menu

That's not at all what I meant.

> So my advice is to restart only with a complete reboot of the game.

How will rebooting the game make a feature, that doesn't exist, available?
