### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by ShortyShorts** [MGeymer/LDYOM#9]
Beta 0.7.2 cannot be installed - with Hoodlum version and with normal versions. Game is crashing no matter what. There's no installation tutorial, in form of a video only text tutorial which doesn't tell anything. Please, help and make video about the installation tutorial. Cheers

Game is crashing when i'll try to launch both DYOM and GTA:SA Base game version. LDYOM is not even showing up on the "New Game". Other things such as DYOM, base game works perfectly without it. Please also make it compatible with SILENT ASI LOADER.

**Comment by ShortyShorts** [comment]
Adding to this. 0.7.0 works - 0.7.1 works - 0.7.2 doesen't work. Runtime error. Base game also doesn't work when 0.7.2 installed - main problem in LDYOM_ASI.SA. Without LDYOM_ASI.SA it works but we can't do nothing in the LDYOM. Same in 0.7.1 pressing U doesn't do nothing.

**Comment by shantanub08** [comment]
It's quite creepy how I was just going to write the exact same thing today (except it working on other versions part)
Just few days ago, I came to know about LDYOM, and tried installing it yesterday, it keeps crashing after "Start New Game"_*_ and after selecting a save game. _(*DYOM is not installed)_

I have Hoodlum version. Tried disabling all mods from modloader, still keeps crashing. I'm on CLEO v4.4.0. SilentPatch Installed with Silent ASI Loader

**Comment by ShortyShorts** [comment]
> It's quite creepy how I was just going to write the exact same thing today (except it working on other versions part) Just few days ago, I came to know about LDYOM, and tried installing it yesterday, it keeps crashing after "Start New Game"_*_ and after selecting a save game. _(*DYOM is not installed)_
> 
> I have Hoodlum version. Tried disabling all mods from modloader, still keeps crashing. I'm on CLEO v4.4.0. SilentPatch Installed with Silent ASI Loader

I think i literally fixed the issue. Install LDYOM versions from the very first - to very last. If not I can send you my GTA copy that actually LDYOM works on it, just pasted randomly LDYOM files to moonloader and nearly everywhere lol. But there's another problem. New version is playing fine, but I can't do objectives / or basic actor animations. From the tutorials I saw, you need to do "Actor Appearance" node, and then from it put other nodes aswell that match it - ex. car routes, paths, animations that you want to play. So I did it, and in the new version there's a bug / or the version is broken - that Actor Appearance is a "problem" that's crashing the mission script (when you start the mission its telling you that mission can't be played succesfully and you need to write something to go back) and turns out Actor Appearance is the problem. It's weird. I thought I can make something from it, but no. And Skic isn't very active on Forums, maybe on Discord but I'll not enter Discord, because people there might be "very cancerous". At this point I suggest if you don't want to do missions in regular DYOM, try to script it in Sanny Builder instead, it's easier and there's alot of tutorials in it. This one is buggy AF. You can check it yourself, i'll upload my game directory with working LDYOM there, so you can check it out by yourself. Make sure you just put MPACK (from the newest version) to GTA:SA User Files / MPACK (you need to have DYOM i think), and incase just put it also outside MPACK5, MPACK folder (GTA SA User Files folder) otherwise it wouldn't work. As i said - pasted it literally everywhere and it worked. The LDYOM_ASI.SA works when you put it to GTA SA/scripts folder - but first you need to install the very first LDYOM version, then the second one with the same file, and then replace the older version file with the newer one. Keep in mind, if you launch my game, you need to launch it two times (sometimes) - if you launch for the first time and it doesn't work - just end the process in Task Manager, and play it again and it works (idk why its happening for me). I'll send the link very soon if it uploads the full GTA Folder. It will be today. Cheers.

Oh hey, if you'll understand it, can you do some LDYOM tutorials? Would love to check it out, and share with GTAForums community if possible! @shantanub08

Here you go: https://easyupload.io/hysbuj

**Comment by shantanub08** [comment]
> Here you go: https://easyupload.io/hysbuj

Hey, thanks for the upload! But it is still crashing. Except now it at least reaches to the loading screen after you start new game and THEN crashes. It seems I may need to change some settings of my monitor or something

> Oh hey, if you'll understand it, can you do some LDYOM tutorials? Would love to check it out, and share with GTAForums community if possible!

I don't think I'm capable of making any tutorials on LDYOM. As you know, I could never even install it so, I think it's best to leave the tutorial stuff to Skic. I mean, how can I make tuts on something I myself don't know 😅 although I'm going to put a lot of time into learning it. My main goal is not to make real missions but just to make a few scenes for a fun GTA Moive (DYOM is such a pain in the brain for it)

> Skic isn't very active on Forums, maybe on Discord but I'll not enter Discord, because people there might be "very cancerous"

Haha, all people can be quite toxic but I can assure you that it's a quite friendly server. There's just one guy who sends everyone invites to his dead DYOM server but he's harmless. Skic is not that much active there either. I kinda expected the LDYOM Forum's tutorial section to have any tutorials 🤣 but oh well

**Comment by shantanub08** [comment]
I just got the solution! (extracted from @ShortyShorts's response):

The **MPACK7** needs to be in **MPACK** folder. The crash was only occurring due to it being in **Documents\GTA San Andreas User Files** whereas it should be in **Documents\GTA San Andreas User Files\MPACK**

However, the U button doesn't do anything when Windowed Mode Mod is installed. So basically I can't use the mod when I'm in windowed mode. Will have to open an issue for it. But you may close this one

**Comment by ShortyShorts** [comment]
> I just got the solution! (extracted from @ShortyShorts's response:
> 
> The **MPACK7** needs to be in **MPACK** folder. The crash was only occurring due to it being in **Documents\GTA San Andreas User Files** whereas it should be in **Documents\GTA San Andreas User Files\MPACK**
> 
> However, the U button doesn't do anything when Windowed Mode Mod is installed. So basically I can't use the mod when I'm in windowed mode. Will have to open an issue for it. But you may close this one

It should work. Try again with something. Mine works, can even provide screenshots [https://i.imgur.com/2YC4yHx.jpg](url)

That actor appearance thing is literally pain in the ass. Test it. Anyway, nice one and yeah i'll close it. If you want to examine more, here you have more screens:
https://i.imgur.com/SL2qBx7.jpg
https://i.imgur.com/9mjNlQW.jpg

That mission doesen't work - its probably in my archive that i sent you, you can check it out - it just doesen't work that way would love to have solution if you can provide me how it will work. Anyway, closing in. Thanks!
